'use strict';
const SUITS = ['♠','♥','♦','♣'];
const SUIT_NAMES = {'♠':'пики','♥':'черви','♦':'бубны','♣':'крести'};
const RED = new Set(['♥','♦']);
const RANKS = [1,2,3,4,5,6,7,8,9,10,11,12,13];
const RANK_LABEL = {1:'A',11:'J',12:'Q',13:'K'};
const PIP_LAYOUTS = {1:[4],2:[1,7],3:[1,4,7],4:[0,2,6,8],5:[0,2,4,6,8],6:[0,2,3,5,6,8],7:[0,2,3,4,5,6,8],8:[0,2,3,5,6,8,1,7],9:[0,2,3,5,6,8,1,4,7],10:[0,2,3,5,6,8,1,7,0,8]};
const THEMES = {
  default:{title:'Дефолтная тема',tag:'Классическая Косынка с привычными картами',back:'K',fig:{11:'Валет',12:'Дама',13:'Король'},desc:'Классика: собирай фундаменты от туза до короля. В колонках клади карты по убыванию и обязательно чередуй цвет масти.'},
  light:{title:'Светлая тема',tag:'Чистый светлый стол без лишних деталей',back:'A',fig:{11:'Office J',12:'Office Q',13:'Office K'},desc:'Правила обычные: черная карта ложится на красную, красная — на черную. Король открывает пустую колонку.'},
  dark:{title:'Темная тема',tag:'Темный системный стиль для вечерней игры',back:'K',fig:{11:'Neon J',12:'Neon Q',13:'Neon K'},desc:'Та же Косынка, но в темной оболочке. Используй подсказку, если стол выглядит заблокированным.'},
  minecraft:{title:'Minecraft style',tag:'Квадратный блочный мир, земляной фон и пиксельные карты',back:'BLOCK',fig:{11:'Крипер',12:'Алекс',13:'Стив'},symbols:{'♠':'◆','♥':'♥','♦':'■','♣':'✚'},desc:'Блочная логика: крипер, Алекс и Стив двигаются как J/Q/K. Цвета всё равно чередуются, а король/Стив занимает пустой слот.'},
  halloween:{title:'Halloween',tag:'Тыквы, темные деревья, ведьмы и ночной туман',back:'PUMPKIN',fig:{11:'Скелет',12:'Ведьма',13:'Маньяк'},symbols:{'♠':'蛛','♥':'♥','♦':'◆','♣':'蝙'},desc:'Мрачный режим: пауки и летучие мыши заменяют часть мастей. Правило боя прежнее: карта бьет карту на 1 младше другого цвета.'},
  kitty:{title:'Hello Kitty style',tag:'Милая розовая тема с авторскими котиками и бантиками',back:'BOW',fig:{11:'Котик J',12:'Принцесса Q',13:'Кот K'},symbols:{'♠':'♠','♥':'♥','♦':'◇','♣':'✿'},desc:'Милая версия: бантики и цветочки выглядят иначе, но играются как обычные масти. Собирай каждую масть отдельно в верхние стопки.'},
  chernobyl:{title:'Чернобыль',tag:'Радиация, пустошь, бетон, мутировавшие растения',back:'RAD',fig:{11:'Сталкер',12:'Мутант',13:'Ликвидатор'},symbols:{'♠':'☢','♥':'♥','♦':'◇','♣':'✣'},desc:'Зона не прощает ошибок: открывай закрытые карты, освобождай колонки под королей и не забывай перебирать сброс.'},
  sponge:{title:'Губка-боб style',tag:'Подводный мир, пузырьки и яркие морские карты',back:'SEA',fig:{11:'Краб',12:'Белка',13:'Губка'},symbols:{'♠':'♠','♥':'♥','♦':'◆','♣':'♣'},desc:'Под водой правила суши: красные и черные чередуются, последовательности перетаскиваются пачками, тузы уходят наверх.'}
};
let state, initialSnapshot, undoStack = [], selected = null, timerId = null, deferredInstallPrompt = null;
const $ = id => document.getElementById(id);
const els = {moves:$('moves'),timer:$('timer'),best:$('best'),stock:$('stock'),waste:$('waste'),foundations:$('foundations'),tableau:$('tableau'),hint:$('hintText'),themeSelect:$('themeSelect'),toast:$('toast'),modal:$('modal'),modalTitle:$('modalTitle'),modalContent:$('modalContent'),themeTitle:$('themeTitle'),themeDescription:$('themeDescription'),themeTagline:$('themeTagline')};
function freshDeck(){let d=[]; for(const s of SUITS) for(const r of RANKS) d.push({suit:s,rank:r,face:false,id:s+r+'-'+crypto.getRandomValues(new Uint32Array(1))[0].toString(36)}); return shuffle(d)}
function shuffle(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function makeGame(deck=freshDeck()){const tableau=Array.from({length:7},()=>[]);let k=0;for(let c=0;c<7;c++){for(let r=0;r<=c;r++){const card=deck[k++];card.face=r===c;tableau[c].push(card)}}return {stock:deck.slice(k).map(c=>({...c,face:false})),waste:[],foundations:{'♠':[],'♥':[],'♦':[],'♣':[]},tableau,moves:0,start:Date.now(),elapsed:0,theme:localStorage.getItem('klondike-theme')||'default',won:false,over:false}}
function snapshot(){return JSON.stringify({stock:state.stock,waste:state.waste,foundations:state.foundations,tableau:state.tableau,moves:state.moves,start:state.start,elapsed:state.elapsed,theme:state.theme,won:state.won,over:state.over})}
function restore(s){state=JSON.parse(s);selected=null;render();}
function pushUndo(){undoStack.push(snapshot()); if(undoStack.length>80) undoStack.shift()}
function newGame(){state=makeGame();initialSnapshot=snapshot();undoStack=[];selected=null;applyTheme(state.theme);startTimer();render();toast('Новая партия началась')}
function restart(){if(!initialSnapshot)return;restore(initialSnapshot);state.start=Date.now();state.elapsed=0;undoStack=[];startTimer();toast('Партия перезапущена')}
function startTimer(){clearInterval(timerId);timerId=setInterval(()=>{if(!state?.won&&!state?.over){state.elapsed=Math.floor((Date.now()-state.start)/1000);els.timer.textContent=formatTime(state.elapsed)}},1000)}
function formatTime(s){return `${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`}
function rankText(r){return RANK_LABEL[r]||String(r)}
function color(card){return RED.has(card.suit)?'red':'black'}
function cardLabel(c){return `${rankText(c.rank)} ${SUIT_NAMES[c.suit]}`}
function top(arr){return arr[arr.length-1]}
function canMoveToFoundation(card){const f=state.foundations[card.suit];return card.face && (card.rank===1 && f.length===0 || top(f)?.rank===card.rank-1)}
function canPlaceOnTableau(card,dest){if(!card.face)return false; if(dest.length===0)return card.rank===13; const t=top(dest);return t.face && color(t)!==color(card) && t.rank===card.rank+1}
function moveWasteToFoundation(){const c=top(state.waste); if(c&&canMoveToFoundation(c)){pushUndo();state.foundations[c.suit].push(state.waste.pop());afterMove('Карта ушла в фундамент');return true}return false}
function moveWasteToTableau(col){const c=top(state.waste); if(c&&canPlaceOnTableau(c,state.tableau[col])){pushUndo();state.tableau[col].push(state.waste.pop());afterMove('Карта перенесена на стол');return true}return false}
function moveTableauToFoundation(col){const c=top(state.tableau[col]); if(c&&canMoveToFoundation(c)){pushUndo();state.foundations[c.suit].push(state.tableau[col].pop());flipLast(col);afterMove('Карта ушла в фундамент');return true}return false}
function moveTableauToTableau(from,index,to){if(from===to)return false;const moving=state.tableau[from].slice(index);if(!moving.length||!moving[0].face)return false;if(canPlaceOnTableau(moving[0],state.tableau[to])){pushUndo();state.tableau[to].push(...moving);state.tableau[from].splice(index);flipLast(from);afterMove('Последовательность перенесена');return true}return false}
function flipLast(col){const t=top(state.tableau[col]); if(t&&!t.face){t.face=true; state.moves++}}
function drawStock(){if(state.stock.length){pushUndo();const c=state.stock.pop();c.face=true;state.waste.push(c);afterMove('Карта открыта из колоды')}else if(state.waste.length){pushUndo();state.stock=state.waste.reverse().map(c=>({...c,face:false}));state.waste=[];afterMove('Сброс возвращен в колоду')}else toast('Колода пуста')}
function afterMove(message){state.moves++;selected=null;render();checkEnd(); if(message) toast(message)}
function undo(){if(!undoStack.length){toast('Отменять нечего');return}restore(undoStack.pop());toast('Ход отменен')}
function render(){document.body.className='theme-'+state.theme;els.moves.textContent=state.moves;els.timer.textContent=formatTime(state.elapsed||0);els.best.textContent=bestText();renderStockWaste();renderFoundations();renderTableau();updateThemeText();}
function clear(el){while(el.firstChild)el.removeChild(el.firstChild)}
function renderStockWaste(){clear(els.stock);clear(els.waste);els.stock.dataset.mark='↻';els.waste.dataset.mark='';els.stock.onclick=drawStock;if(state.stock.length)els.stock.appendChild(cardEl({...top(state.stock),face:false}, {source:'stock'}));if(state.waste.length){const visible=state.waste.slice(-3);visible.forEach((c,i)=>{const el=cardEl(c,{source:'waste',index:state.waste.length-visible.length+i});el.style.left=`${i*7}px`;el.style.zIndex=i+1;els.waste.appendChild(el)})}}
function renderFoundations(){clear(els.foundations);for(const s of SUITS){const p=document.createElement('div');p.className='pile foundation';p.dataset.suit=s;p.dataset.mark=themeSymbol(s);p.ondragover=e=>e.preventDefault();p.ondrop=e=>handleDrop(e,{type:'foundation',suit:s});const c=top(state.foundations[s]);if(c)p.appendChild(cardEl(c,{source:'foundation',suit:s,index:state.foundations[s].length-1}));els.foundations.appendChild(p)}}
function renderTableau(){clear(els.tableau);state.tableau.forEach((col,ci)=>{const div=document.createElement('div');div.className='column';div.dataset.col=ci;div.style.height=`calc(var(--card-h) + ${Math.max(0,col.length-1)} * clamp(23px,3.2vw,38px))`;div.ondragover=e=>e.preventDefault();div.ondrop=e=>handleDrop(e,{type:'tableau',col:ci,index:col.length});div.onclick=e=>{if(e.target===div&&selected){if(selected.source==='waste')moveWasteToTableau(ci);else if(selected.source==='tableau')moveTableauToTableau(selected.col,selected.index,ci)}};col.forEach((c,i)=>{const el=cardEl(c,{source:'tableau',col:ci,index:i});el.style.top=`calc(${i} * clamp(23px,3.2vw,38px))`;el.style.zIndex=i+1;div.appendChild(el)});els.tableau.appendChild(div)})}
function cardEl(card,meta){const el=document.createElement('div');el.className='card '+(card.face?color(card):'face-down');el.dataset.id=card.id;el.dataset.meta=JSON.stringify(meta);el.dataset.back=THEMES[state.theme].back||'K';el.draggable=!!card.face;el.addEventListener('dragstart',e=>{e.dataTransfer.setData('text/plain',JSON.stringify(meta));setTimeout(()=>el.classList.add('selected'),0)});el.addEventListener('dragend',()=>el.classList.remove('selected'));el.addEventListener('click',e=>{e.stopPropagation();handleCardClick(meta)});if(!card.face)return el;const sym=themeSymbol(card.suit);el.innerHTML=`<div class="corner tl"><span>${rankText(card.rank)}</span><span class="suit">${sym}</span></div><div class="corner br"><span>${rankText(card.rank)}</span><span class="suit">${sym}</span></div><div class="art">${artHTML(card,sym)}</div>`;if(isSelected(meta))el.classList.add('selected');return el}
function themeSymbol(s){return THEMES[state.theme].symbols?.[s]||s}
function artHTML(c,sym){if(c.rank>10||c.rank===1){const fig=c.rank===1?aceFigure(c.suit):THEMES[state.theme].fig[c.rank];return `<div class="figure" data-figure="${figIcon(c.rank,c.suit)}" data-caption="${fig}"></div>`}const cells=Array.from({length:9},(_,i)=>PIP_LAYOUTS[c.rank].includes(i)?`<span class="pip">${sym}</span>`:'<span class="pip blank">.</span>').join('');return `<div class="pip-grid">${cells}</div>`}
function aceFigure(s){return 'Туз '+SUIT_NAMES[s]}
function figIcon(r,s){const m={default:{1:'A',11:'J',12:'Q',13:'K'},light:{1:'A',11:'⌘',12:'◇',13:'★'},dark:{1:'A',11:'◆',12:'◈',13:'✦'},minecraft:{1:'▣',11:'▦',12:'▧',13:'▥'},halloween:{1:'☾',11:'骨',12:'W',13:'X'},kitty:{1:'♡',11:'=^.^=',12:'BOW',13:'♕'},chernobyl:{1:'☢',11:'M',12:'X',13:'R'},sponge:{1:'◎',11:'K',12:'S',13:'B'}};return m[state.theme]?.[r]||rankText(r)}
function isSelected(meta){return selected&&JSON.stringify(selected)===JSON.stringify(meta)}
function handleCardClick(meta){if(state.won||state.over)return;if(meta.source==='stock'){drawStock();return}if(meta.source==='waste'){if(moveWasteToFoundation())return;selected= isSelected(meta)?null:meta;render();return}if(meta.source==='foundation'){selected=null;render();return}const col=state.tableau[meta.col], card=col[meta.index];if(!card.face&&meta.index===col.length-1){pushUndo();card.face=true;afterMove('Карта открыта');return}if(selected){if(selected.source==='waste'&&moveWasteToTableau(meta.col))return;if(selected.source==='tableau'&&moveTableauToTableau(selected.col,selected.index,meta.col))return;selected=null;render();return}if(meta.index===col.length-1&&moveTableauToFoundation(meta.col))return;selected=meta;render()}
function handleDrop(e,target){e.preventDefault();let meta;try{meta=JSON.parse(e.dataTransfer.getData('text/plain'))}catch{return}if(target.type==='foundation'){if(meta.source==='waste')moveWasteToFoundation();if(meta.source==='tableau')moveTableauToFoundation(meta.col)}else if(target.type==='tableau'){if(meta.source==='waste')moveWasteToTableau(target.col);if(meta.source==='tableau')moveTableauToTableau(meta.col,meta.index,target.col)}}
function findHint(){const w=top(state.waste);if(w&&canMoveToFoundation(w))return {text:`Положи ${cardLabel(w)} из сброса в верхний фундамент.`,meta:{source:'waste',index:state.waste.length-1}};for(let i=0;i<7;i++){const c=top(state.tableau[i]);if(c&&canMoveToFoundation(c))return {text:`Положи ${cardLabel(c)} из ${i+1}-й колонки в фундамент.`,meta:{source:'tableau',col:i,index:state.tableau[i].length-1}}}if(w){for(let j=0;j<7;j++)if(canPlaceOnTableau(w,state.tableau[j]))return {text:`Перенеси ${cardLabel(w)} из сброса в ${j+1}-ю колонку.`,meta:{source:'waste',index:state.waste.length-1}}}for(let i=0;i<7;i++){for(let k=0;k<state.tableau[i].length;k++){const c=state.tableau[i][k];if(!c.face)continue;for(let j=0;j<7;j++)if(i!==j&&canPlaceOnTableau(c,state.tableau[j]))return {text:`Перенеси ${cardLabel(c)} из ${i+1}-й колонки в ${j+1}-ю колонку.`,meta:{source:'tableau',col:i,index:k}}}}if(state.stock.length)return {text:'Открой следующую карту из колоды.',meta:{source:'stock'}};if(state.waste.length)return {text:'Кликни по пустой колоде, чтобы вернуть сброс обратно.',meta:{source:'stock'}};return null}
function showHint(){const h=findHint();if(!h){els.hint.textContent='Ходов не найдено. Партия, похоже, заблокирована.';state.over=true;render();showEnd('Game over');return}els.hint.textContent=h.text;selected=h.meta;render();highlight(h.meta)}
function highlight(meta){setTimeout(()=>{let selector;if(meta.source==='waste')selector='#waste .card:last-child';else if(meta.source==='stock')selector='#stock';else selector=`.column[data-col="${meta.col}"] .card:nth-child(${meta.index+1})`;document.querySelector(selector)?.classList.add('hinted')},40)}
function checkEnd(){if(Object.values(state.foundations).every(f=>f.length===13)){state.won=true;saveBest();render();document.querySelectorAll('.card').forEach(c=>c.classList.add('win-card'));showEnd('You won')}else if(!findHint()&&!state.stock.length&&!state.waste.length){state.over=true;render();showEnd('Game over')}}
function showEnd(text){clearInterval(timerId);openModal(text,`<p><b>${text}</b></p><p>Ходы: ${state.moves}. Время: ${formatTime(state.elapsed)}.</p><p>Можно начать новую игру или перезапустить текущую раздачу.</p>`)}
function bestKey(){return 'klondike-best-'+state.theme}
function bestText(){const b=JSON.parse(localStorage.getItem(bestKey())||'null');return b?`${b.moves}/${formatTime(b.time)}`:'—'}
function saveBest(){const b=JSON.parse(localStorage.getItem(bestKey())||'null');if(!b||state.moves<b.moves||(state.moves===b.moves&&state.elapsed<b.time)){localStorage.setItem(bestKey(),JSON.stringify({moves:state.moves,time:state.elapsed}));toast('Новый рекорд темы!')}}
function updateThemeText(){const t=THEMES[state.theme];els.themeTitle.textContent=t.title;els.themeDescription.textContent=t.desc;els.themeTagline.textContent=t.tag;els.themeSelect.value=state.theme;document.querySelector('meta[name="theme-color"]').setAttribute('content',getComputedStyle(document.body).getPropertyValue('--card-back')||'#101624')}
function applyTheme(v){state.theme=v;localStorage.setItem('klondike-theme',v);document.body.className='theme-'+v;updateThemeText();render()}
function rulesHTML(){const t=THEMES[state.theme];return `<p>${t.desc}</p><ul><li>Цель — собрать 4 верхние стопки от туза до короля.</li><li>В колонках карты идут по убыванию: K, Q, J, 10…</li><li>Цвета чередуются: красная карта на черную, черная на красную.</li><li>В пустую колонку можно положить только короля или пачку, начинающуюся с короля.</li><li>Закрытая карта открывается, когда становится верхней.</li></ul>`}
function iosHTML(){return `<p>На iPhone сайт устанавливается как приложение через Safari:</p><ol><li>Открой страницу игры в Safari.</li><li>Нажми кнопку «Поделиться» внизу экрана.</li><li>Выбери «На экран Домой».</li><li>Подтверди название «Косынка».</li></ol><p>После этого игра откроется во весь экран, а иконка будет выглядеть как обычное приложение.</p>`}
function installHTML(){return `<p>Это PWA-приложение, поэтому скачивание происходит без exe-файла.</p><ul><li>Windows/Chrome/Edge: нажми «Скачать приложение» или значок установки в адресной строке.</li><li>macOS/Safari/Chrome: открой меню браузера и выбери добавление на Dock/установку приложения, если браузер поддерживает PWA.</li><li>iOS: используй отдельную кнопку «На iPhone» с инструкцией.</li></ul><p>Все файлы лежат локально в репозитории и работают через GitHub Pages.</p>`}
function openModal(title,html){els.modalTitle.textContent=title;els.modalContent.innerHTML=html;els.modal.showModal()}
function toast(msg){els.toast.textContent=msg;els.toast.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>els.toast.classList.remove('show'),2200)}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstallPrompt=e;});
$('installBtn').onclick=async()=>{if(deferredInstallPrompt){deferredInstallPrompt.prompt();await deferredInstallPrompt.userChoice;deferredInstallPrompt=null}else openModal('Скачать приложение',installHTML())};
$('iosBtn').onclick=()=>openModal('Добавить на главный экран iPhone',iosHTML());
$('rulesBtn').onclick=()=>openModal('Как играть',rulesHTML());
$('closeModal').onclick=()=>els.modal.close();
$('newGameBtn').onclick=newGame;$('restartBtn').onclick=restart;$('undoBtn').onclick=undo;$('hintBtn').onclick=showHint;els.themeSelect.onchange=e=>applyTheme(e.target.value);
if('serviceWorker' in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}))}
newGame();
